name: ipot_qr_ordering
description: QR ordering app for the IPOT mobile developer technical test.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  get_it: ^8.2.0
  intl: ^0.20.2
  mobile_scanner: ^7.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/mock/
